apiVersion: v1
kind: Service
metadata:
  name: golang
spec:
  selector:
    app: golangolang-app
  type: NodePort
  ports:
    - name: golang
      port: 8080
      targetPort: 8080
      protocol: "TCP"